/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-core:java/core/repository/EntityRepository.e.vm.java
 */
package net.leidra.demo.repository;

import net.leidra.demo.domain.Products;

public interface ProductsRepository extends Repository<Products, Integer> {

}