$output.resource("application.yml")##
security:
    basic:
        enabled: false

spring:
    datasource:
        driver-class-name: @jdbc.driver@
        url: @jdbc.url@
        name:
        username: @jdbc.user@
        password: @jdbc.password@
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

        database-platform: @hibernate.dialect@
        database: @jdbc.artifactId@
        show_sql: @hibernate.show.sql@
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    messages:
        cache-seconds: 1

server:
    port: 8080