/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-services:java/services/services/ServicesPackageProvider.p.vm.java
 */
package net.leidra.demo.service;

public interface ServicesPackageProvider {
}
