/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-core:java/core/config/CoreConfiguration.p.vm.java
 */
package net.leidra.demo.domain.config;

import net.leidra.demo.core.domain.EntitiesPackageProvider;
import net.leidra.demo.core.repositories.RepositoriesPackageProvider;

import org.springframework.boot.orm.jpa.EntityScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@Configuration
@EntityScan(basePackageClasses = EntitiesPackageProvider.class)
@EnableJpaRepositories(basePackageClasses = RepositoriesPackageProvider.class)
public class CoreConfiguration {
}