/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-shared:java/core/domain/Dto.e.vm.java
 */
package net.leidra.demo.shared.dtos;

import java.io.Serializable;
import java.util.Date;
import java.util.logging.Logger;

import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;

import com.google.common.base.Objects;
import com.jaxio.jpa.querybyexample.Identifiable;

public class BrandsDtoDto implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(BrandsDto.class.getName());

    // Raw attributes
    private Integer id;
    private String name;
    private Date createdDate;
    private Date lastModifiedName;

    @Override
    public String className() {
        return Brands.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public BrandsDto id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [name] ------------------------

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BrandsDto name(String name) {
        setName(name);
        return this;
    }

    // -- [createdDate] ------------------------

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public BrandsDto createdDate(Date createdDate) {
        setCreatedDate(createdDate);
        return this;
    }

    // -- [lastModifiedName] ------------------------

    public Date getLastModifiedName() {
        return lastModifiedName;
    }

    public void setLastModifiedName(Date lastModifiedName) {
        this.lastModifiedName = lastModifiedName;
    }

    public BrandsDto lastModifiedName(Date lastModifiedName) {
        setLastModifiedName(lastModifiedName);
        return this;
    }

    /**
     * Apply the default values.
     */
    public BrandsDto withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof BrandsDto && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getName());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warning("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this BrandsDto instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("name", getName()) //
                .add("createdDate", getCreatedDate()) //
                .add("lastModifiedName", getLastModifiedName()) //
                .toString();
    }
}
