/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-shared:java/core/domain/Dto.e.vm.java
 */
package net.leidra.demo.shared.dtos;

import java.io.Serializable;
import java.util.Date;
import java.util.logging.Logger;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;

import com.google.common.base.Objects;

public class ProductsDto implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(ProductsDto.class.getName());

    // Raw attributes
    private Integer id;
    private String name;
    private Date createdDate;
    private Date lastModifiedName;

    // Many to one
    private BrandsDto brand;
    private UsersDto user;

    // -- [id] ------------------------

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ProductsDto id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [name] ------------------------

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ProductsDto name(String name) {
        setName(name);
        return this;
    }

    // -- [createdDate] ------------------------

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public ProductsDto createdDate(Date createdDate) {
        setCreatedDate(createdDate);
        return this;
    }

    // -- [lastModifiedName] ------------------------

    public Date getLastModifiedName() {
        return lastModifiedName;
    }

    public void setLastModifiedName(Date lastModifiedName) {
        this.lastModifiedName = lastModifiedName;
    }

    public ProductsDto lastModifiedName(Date lastModifiedName) {
        setLastModifiedName(lastModifiedName);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Products.brand ==> Brands.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    public BrandsDto getBrand() {
        return brand;
    }

    /**
     * Set the {@link #brand} without adding this Products instance on the passed {@link #brand}
     */
    public void setBrand(BrandsDto brand) {
        this.brand = brand;
    }

    public ProductsDto brand(BrandsDto brand) {
        setBrand(brand);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Products.user ==> Users.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    public UsersDto getUser() {
        return user;
    }

    /**
     * Set the {@link #user} without adding this Products instance on the passed {@link #user}
     */
    public void setUser(UsersDto user) {
        this.user = user;
    }

    public ProductsDto user(UsersDto user) {
        setUser(user);
        return this;
    }

    /**
     * Apply the default values.
     */
    public ProductsDto withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ProductsDto && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getName());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warning("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this ProductsDto instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("name", getName()) //
                .add("createdDate", getCreatedDate()) //
                .add("lastModifiedName", getLastModifiedName()) //
                .toString();
    }
}
