/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-core:java/core/domain/Entity.e.vm.java
 */
package net.leidra.demo.core.domain;

import static javax.persistence.TemporalType.TIMESTAMP;

import java.io.Serializable;
import java.util.Date;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.Objects;
import com.jaxio.jpa.querybyexample.Identifiable;

@Entity
@Table(name = "`USERS`")
public class Users implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Users.class.getName());

    // Raw attributes
    private Integer id;
    private String name;
    private String password;
    private Date createdDate;
    private Date lastModifiedName;

    @Override
    public String className() {
        return Users.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "ID", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Users id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [name] ------------------------

    @NotEmpty
    @Size(max = 50)
    @Column(name = "NAME", nullable = false, unique = true, length = 50)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Users name(String name) {
        setName(name);
        return this;
    }

    // -- [password] ------------------------

    @NotEmpty
    @Size(max = 250)
    @Column(name = "`PASSWORD`", nullable = false, length = 250)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Users password(String password) {
        setPassword(password);
        return this;
    }

    // -- [createdDate] ------------------------

    @NotNull
    @Column(name = "CREATED_DATE", nullable = false, length = 23)
    @Temporal(TIMESTAMP)
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Users createdDate(Date createdDate) {
        setCreatedDate(createdDate);
        return this;
    }

    // -- [lastModifiedName] ------------------------

    @NotNull
    @Column(name = "LAST_MODIFIED_NAME", nullable = false, length = 23)
    @Temporal(TIMESTAMP)
    public Date getLastModifiedName() {
        return lastModifiedName;
    }

    public void setLastModifiedName(Date lastModifiedName) {
        this.lastModifiedName = lastModifiedName;
    }

    public Users lastModifiedName(Date lastModifiedName) {
        setLastModifiedName(lastModifiedName);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Users withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Users && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getName());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warning("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this Users instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("name", getName()) //
                .add("password", "XXXX") //
                .add("createdDate", getCreatedDate()) //
                .add("lastModifiedName", getLastModifiedName()) //
                .toString();
    }
}
