/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-core:java/core/domain/EntitiesPackageProvider.p.vm.java
 */
package net.leidra.demo.domain;

public interface EntitiesPackageProvider {
}
