/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-services:java/services/config/ServicesConfiguration.p.vm.java
 */
package net.leidra.demo.config;

import net.leidra.pm.core.services.ServicesPackageProvider;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan(basePackageClasses = ServicesPackageProvider.class)
public class ServicesConfiguration {
}