---
-- Example Schema
--

DROP ALL OBJECTS;

--CREATE SEQUENCE hibernate_sequence START WITH 1000;

CREATE TABLE brands(
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	created_date TIMESTAMP NOT NULL,
	last_modified_name TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE users(
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(250) NOT NULL,
	created_date TIMESTAMP NOT NULL,
	last_modified_name TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE products(
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	brand_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	created_date TIMESTAMP NOT NULL,
	last_modified_name TIMESTAMP NOT NULL,

	FOREIGN KEY (brand_id) REFERENCES brands(id),
	FOREIGN KEY (user_id) REFERENCES users(id),
	PRIMARY KEY(id)
);